name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Check the Settings page for version info
      placeholder: e.g., v2.0.0
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Device
      placeholder: e.g., Chrome on Android / Safari on iPhone
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs (if relevant)
      description: Logs can be found in Settings → Backend/Frontend Logs
      render: text
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues first
          required: true
