name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What are you trying to accomplish?
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      placeholder: It would be great if...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - AI/Detection
        - UI/UX
        - Capture Workflow
        - Location Management
        - Settings
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or any other relevant info
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues first
          required: true
